require ["fileinto", "vacation"];

# SPAM
if header :contains "X-Spam-Flag" ["YES"] { fileinto "Junk"; stop; }

# Vacation
if not header :contains "Precedence" ["bulk","list"] {
   vacation :days 7 :addresses ["user@example.com"] :subject "Vacation" "Hey,

This is autogenerated message to inform you, that I'm on vacations in a middle of nowhere (no current, no GSM range, and best of all - NO INTERNET at all), and it's almost impossible to reach me.";
}


